let s = "srikanth";
document.write(s.indexOf('t') + "<br>");
document.write(s.charAt(4) + "<br>");
document.write(s.substring(3,5) + "<br>");
document.write(s.charCodeAt(6) + "<br>");
document.write(s.slice(2,4) + "<br>");
document.write(s.toUpperCase() + "<br>");
document.write(s.concat("vempalli") + "<br>");
document.write(s.includes("sr") + "<br>");
document.write(s.split("*") );
